services:
  traefik:
    image: traefik:2.9
    command:
      --providers.docker=true
      --providers.docker.watch=true
      --providers.docker.swarmMode=false
      --providers.docker.exposedByDefault=false
      --entryPoints.http.address=:80
      --api
      --api.dashboard=true
    ports:
      - "80:80"
    networks:
      - esforce-dev
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.traefik.rule=Host(`traefik.esforce.localhost`)
      - traefik.http.routers.traefik.entryPoints=http
      - traefik.http.services.traefik.loadBalancer.server.port=80
      - traefik.http.routers.traefik.service=api@internal

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "63791:6379"

  # ===============================
  # ===== SITE ====================
  # ===============================
  site_db:
    image: mariadb:11.4.3
    environment:
      MYSQL_USER: site
      MYSQL_PASSWORD: site
      MYSQL_DATABASE: site
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MARIADB_ROOT_PASSWORD: site
    volumes:
      - site_db:/var/lib/mysql:Z
    ports:
      - "33061:3306"

  site-node:
    container_name: site-node
    build:
      context: docker/dev/site/node
      dockerfile: 20.dockerfile
    user: node
    environment:
      DEV_HOSTNAME: esforce.localhost
      API_BASE_URL: https://api.esforce.localhost
      API_URL_PREFIX: /api
    volumes:
      - ./site:/app
    working_dir: /app

  site:
    build:
      context: docker/dev/site/nginx
    volumes:
      - ./site:/app:ro
      - ./docker/dev/site/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/dev/site/nginx/nginxconfig.io:/etc/nginx/nginxconfig.io:ro
      - ./docker/dev/site/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/dev/site/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    networks:
      - esforce-dev
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=esforce-dev
      # http
      - traefik.http.routers.site.entryPoints=http
      - traefik.http.routers.site.rule=Host(`api.esforce.localhost`)
      # ...
      - traefik.http.services.site.loadBalancer.server.port=80
    depends_on:
      - site-php-fpm

  site-php-fpm:
    build:
      context: docker/dev/site
      dockerfile: php-fpm/83.dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=SITE
      # .env
      DATABASE_URL: mysql://site:site@site_db/site?serverVersion=11.4.3-MariaDB
      REDIS_DSN: redis://redis
    volumes:
      - ./site:/app
    depends_on:
      - site_db
      - redis

  site-php-cli:
    build:
      context: docker/dev/site
      dockerfile: php-cli/83.dockerfile
      args:
        UUID: ${UUID:-1000}
        UGID: ${UGID:-1000}
    environment:
      UUID: ${UUID:-1000}
      UGID: ${UGID:-1000}
      APP_ENV: dev
      APP_DEBUG: 1
      # .env
      DATABASE_URL: mysql://site:site@site_db/site?serverVersion=11.4.3-MariaDB
      REDIS_DSN: redis://redis
    volumes:
      - ./site:/app
    depends_on:
      - site_db
      - redis
    links:
      - redis

  # ===============================
  # ===== FRONT ===================
  # ===============================
  front:
    image: nginx:1.26.2-alpine
    working_dir: /app
    volumes:
      - ./front:/app
      - ./docker/dev/front/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/dev/front/nginx/nginxconfig.io:/etc/nginx/nginxconfig.io:ro
      - ./docker/dev/front/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/dev/front/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    networks:
      - esforce-dev
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=esforce-dev
      # http
      - traefik.http.routers.front.entryPoints=http
      - traefik.http.routers.front.rule=Host(`esforce.localhost`)
      # ...
      - traefik.http.services.front.loadBalancer.server.port=80
    depends_on:
      - front-node

  front-node:
    container_name: front-node
    build:
      context: docker/dev/front/node
      dockerfile: 20.dockerfile
    user: node
    working_dir: /app
    volumes:
      - ./front:/app
    environment:
      WDS_SOCKET_PORT: 0
      NODE_ENV: development
      API_BASE_URL: http://api.esforce.localhost
      SITE_HOST: 0.0.0.0
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn dev --host 0.0.0.0"
    tty: true

networks:
  esforce-dev:
    name: esforce-dev

volumes:
  site_db:
